compatibility_date = "2022-01-06"
main = "main.ts"

[durable_objects]
bindings = [
  {name = "CRYPTID_PORTFOLIO", class_name = "Portfolio"},
]

[[migrations]]
new_classes = ["Portfolio"] 
tag = "v1" # Should be unique for each entry
