
#:schema node_modules/wrangler/config-schema.json
name = "cryptid"
pages_build_output_dir = "./build/client"
compatibility_date = "2024-05-12"

[[d1_databases]]
binding = "DB"
database_name = "d1-cryptid-app"
database_id = "b9361fa1-0198-479a-af47-dc88951ecb67"
migrations_dir = "./migrations"
